export type VisaDetail = {
  title: string;
  country: string;
  slug: string;
  countrySlug: string;
  overview: string;
  processing: string;
  fee: string;
  eligibility: string[];
  documents: string[];
  steps: string[];
  benefits: string[];
  image: string;
  accentColor: string;
};

export const visaData: VisaDetail[] = [
  // ─── CANADA ───────────────────────────────────────────────────────────────
  {
    title: "Canada PR Visa", country: "Canada", slug: "pr-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "A Canada Permanent Resident Visa grants non-citizens the right to live, work, and study in Canada indefinitely. Valid for 5 years, it is a direct pathway to Canadian citizenship after 3 years of residency.",
    processing: "Express Entry: 5–7 months · PNP: 8–20 months",
    fee: "CAD 2,340 (single) · CAD 4,680 (couple)",
    eligibility: ["Age 18–45", "CLB 7 in English or French (IELTS/PTE)", "Minimum 1 year skilled work experience (TEER 0–3)", "Education equivalent to Canadian secondary or higher", "Proof of settlement funds: CAD 15,263+ (single applicant)", "Medical exam and police clearance certificate"],
    documents: ["Valid passport", "IELTS/PTE score card", "Educational Credential Assessment (ECA)", "Work experience letters", "Bank statements (proof of settlement funds)", "Police Clearance Certificate", "Medical examination report"],
    steps: ["Check eligibility & gather documents", "Take IELTS/PTE language test", "Create Express Entry profile", "Receive Invitation to Apply (ITA)", "Submit PR application with all documents", "Provide biometrics", "Complete medical & security checks", "Receive PR approval & card"],
    benefits: ["Universal healthcare access", "Free education for children", "Work anywhere in Canada", "Sponsor family members", "Eligible for citizenship after 3 years", "Retirement & social security benefits"],
  },
  {
    title: "Canada Express Entry", country: "Canada", slug: "express-entry", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada's Express Entry is the fastest immigration system managing applications for Federal Skilled Worker, Federal Skilled Trades, and Canadian Experience Class. Draws happen regularly and top CRS scorers receive an Invitation to Apply.",
    processing: "5–7 months after receiving ITA",
    fee: "CAD 2,340 (principal applicant)",
    eligibility: ["Skilled work experience (TEER 0–3)", "Language proficiency CLB 7+", "Educational Credential Assessment", "Proof of settlement funds", "No inadmissibility issues"],
    documents: ["Valid passport", "IELTS/PTE results", "ECA report", "Job offer letter (if applicable)", "Work experience letters", "Bank statements"],
    steps: ["Create Express Entry profile", "Receive Comprehensive Ranking System (CRS) score", "Wait for draw or improve score", "Receive Invitation to Apply (ITA)", "Submit complete PR application within 60 days", "Attend biometrics & medical exam", "Receive COPR (Confirmation of PR)"],
    benefits: ["Fastest PR route (~6 months)", "No job offer required", "Includes spouse & dependents", "Pathway to Canadian citizenship", "Work anywhere in Canada"],
  },
  {
    title: "Canada Work Visa", country: "Canada", slug: "work-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada has over 1 million job vacancies and actively recruits skilled workers globally. A Canadian work permit allows you to work for a specific employer or anywhere in Canada with an open work permit.",
    processing: "4 weeks – 6 months",
    fee: "CAD 155 (work permit) + CAD 85 (biometrics)",
    eligibility: ["Valid job offer from a Canadian employer", "Minimum 2 years skilled work experience (NOC TEER 0–3)", "LMIA or LMIA-exempt position", "Valid passport (6+ months)", "Police clearance & medical exam"],
    documents: ["IMM 1295 application form", "Valid passport", "Job offer / LMIA document", "Work experience letters", "Educational certificates", "Passport photos", "Proof of payment"],
    steps: ["Identify your NOC code", "Secure job offer from Canadian employer", "Employer obtains LMIA (if required)", "Gather all documents", "Submit work permit application online", "Provide biometrics", "Complete medical exam", "Receive work permit approval"],
    benefits: ["Average salary CAD 50,000–60,000/year", "Bring spouse & dependents", "Spouse eligible for open work permit", "Children can study without separate permit", "Pathway to PR via Express Entry / CEC"],
  },
  {
    title: "Canada Student Visa", country: "Canada", slug: "student-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada is home to 427,000 Indian students with 8 universities in the global top 200. Students can work 24 hours/week during studies and receive a Post-Graduation Work Permit (PGWP) for up to 3 years.",
    processing: "3–5 weeks (online application)",
    fee: "CAD 150 (study permit) + CAD 85 (biometrics)",
    eligibility: ["Acceptance from a Designated Learning Institution (DLI)", "Minimum 60% in last qualifying exam", "IELTS overall 6.0 (5.5 in each band)", "Proof of funds: CAD 20,635/year (excl. tuition)", "Valid passport", "Clean immigration history"],
    documents: ["DLI acceptance letter", "Valid passport", "IELTS/TOEFL scores", "Bank statements (proof of funds)", "Statement of Purpose (SOP)", "Academic transcripts & certificates", "Provincial Attestation Letter (PAL) if required"],
    steps: ["Get acceptance from a DLI", "Gather all required documents", "Submit online application via IRCC", "Provide biometrics at VAC", "Await study permit decision", "Receive study permit & travel to Canada"],
    benefits: ["Work 24 hrs/week during studies", "Full-time work during holidays", "PGWP up to 3 years after graduation", "Pathway to PR via Express Entry", "Access to world-class universities (U of T, UBC, McGill)"],
  },
  {
    title: "Canada PNP", country: "Canada", slug: "pnp", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada's Provincial Nominee Program (PNP) allows individual provinces and territories to nominate immigrants with skills needed in their region. Over 80 PNP streams exist across Ontario, BC, Alberta, Saskatchewan, and more.",
    processing: "8–20 months",
    fee: "CAD 2,340 (federal PR application)",
    eligibility: ["Skills matching provincial needs", "Work experience in in-demand occupation", "Language proficiency (varies by province)", "Intent to live in nominating province", "Meet age and education criteria"],
    documents: ["Valid passport", "Provincial nomination certificate", "Work experience documents", "Language test scores", "Educational credentials (ECA)", "Proof of funds", "Police clearance & medical"],
    steps: ["Research provincial streams matching your profile", "Apply to province for nomination", "Receive provincial nomination certificate", "Submit federal PR application (Express Entry or paper-based)", "Complete biometrics & medical", "Receive PR approval"],
    benefits: ["Additional 600 CRS points via Express Entry", "Province-specific streams for various profiles", "Lower CRS score requirement than federal draws", "Pathway to permanent residency", "Opportunity to settle in a chosen province"],
  },
  {
    title: "Canada Business Visa", country: "Canada", slug: "business-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada's Business/Investor visa is for entrepreneurs, investors, and self-employed persons looking to establish or invest in a Canadian business. Various streams exist at federal and provincial levels.",
    processing: "12–35 months",
    fee: "CAD 1,575–2,140",
    eligibility: ["Proven business ownership or senior management experience", "Net worth meeting program minimums", "Intent and ability to establish/purchase a business", "Language proficiency (varies by program)", "Medical & security clearances"],
    documents: ["Comprehensive business plan", "Proof of business ownership/management", "Financial statements & net worth proof", "Bank statements", "Valid passport", "Police clearance", "Language test scores"],
    steps: ["Choose appropriate business immigration stream", "Prepare comprehensive business plan", "Submit Expression of Interest (EOI)", "Receive invitation from province/federal", "Submit full application with business plan", "Provide biometrics & medical", "Receive approval & establish business in Canada"],
    benefits: ["PR for investor/entrepreneur & family", "Freedom to run your own business", "Access to Canadian markets", "Children get free education", "Healthcare benefits for entire family", "Pathway to citizenship"],
  },
  {
    title: "Canada Visit Visa", country: "Canada", slug: "visit-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "A Canada Visitor Visa (Temporary Resident Visa) allows Indian citizens to travel to Canada for tourism, family visits, or short business trips. Stays are permitted for up to 6 months per visit.",
    processing: "57–71 days from India",
    fee: "CAD 100 (visa) + CAD 85 (biometrics) ≈ INR 8,329",
    eligibility: ["Valid passport (6+ months validity)", "Sufficient funds: CAD 2,500–5,000", "Strong ties to India (job, family, property)", "Clean immigration record", "Clear purpose of visit"],
    documents: ["Valid passport", "Completed application form", "Recent passport photographs", "Bank statements (6 months)", "Salary slips & income tax returns", "Flight & hotel booking confirmation", "Letter of invitation (if visiting family)", "Employment letter"],
    steps: ["Verify eligibility requirements", "Compile all documents", "Create IRCC online account", "Complete & submit application online", "Pay visa fee online", "Schedule biometrics at VAC", "Await decision (57–71 days)", "Travel to Canada on approval"],
    benefits: ["Stay up to 6 months per visit", "Multiple-entry visa valid up to 10 years", "Super Visa available for parents (5 years per visit)", "Covers tourism, family visits & business meetings"],
  },
  {
    title: "Canada Digital Nomad Visa", country: "Canada", slug: "digital-nomad-visa", countrySlug: "canada",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80&auto=format&fit=crop",
    accentColor: "red",
    overview: "Canada's Digital Nomad stream allows remote workers employed by foreign companies to live and work in Canada temporarily. This is part of Canada's effort to attract global talent.",
    processing: "4–8 weeks",
    fee: "CAD 155",
    eligibility: ["Remote employment with a non-Canadian company", "Minimum salary threshold (varies)", "Valid passport", "No criminal record", "Proof of remote work arrangement"],
    documents: ["Employment contract confirming remote work", "Employer letter confirming remote status", "Proof of income", "Valid passport", "Bank statements", "Travel insurance"],
    steps: ["Confirm eligibility for the stream", "Gather employment & income documents", "Submit work permit application", "Provide biometrics", "Receive permit approval", "Travel & work remotely from Canada"],
    benefits: ["Live in Canada while working for foreign employer", "Experience Canadian lifestyle & culture", "Explore PR pathway options", "Access to provincial healthcare", "Family members may accompany"],
  },

  // ─── AUSTRALIA ───────────────────────────────────────────────────────────
  {
    title: "Australia PR Visa", country: "Australia", slug: "pr-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "Australia's skilled migration program offers permanent residency to skilled workers through a points-based system. Minimum 65 points required with processing in 6–12 months.",
    processing: "6–12 months",
    fee: "AUD 4,640 (primary applicant)",
    eligibility: ["Under 45 years of age", "Minimum 65 points on points test", "Occupation on skilled occupation list (MLTSSL/STSOL)", "Positive skills assessment by relevant authority", "English proficiency (IELTS 6+)", "Medical & character clearances"],
    documents: ["Valid passport", "Skills assessment result", "IELTS/PTE scores", "Work experience letters", "Educational certificates", "Police clearance", "Medical examination"],
    steps: ["Check occupation on skilled list", "Get skills assessed by relevant authority", "Sit IELTS/PTE exam", "Submit Expression of Interest (SkillSelect)", "Receive state nomination or direct invitation", "Lodge PR visa application", "Medical & biometrics", "Receive PR grant"],
    benefits: ["Live & work permanently in Australia", "Medicare public healthcare access", "Free schooling for children", "Sponsor family members", "Pathway to Australian citizenship after 4 years"],
  },
  {
    title: "Australia Skilled Migration", country: "Australia", slug: "skilled-migration", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "Australia's Skilled Migration program includes Subclass 189, 190, and 491 visas for skilled workers. It uses a points-based SkillSelect system where top scorers receive invitations to apply.",
    processing: "6–12 months",
    fee: "AUD 4,640",
    eligibility: ["Age under 45", "65+ points on skills assessment", "Occupation on MLTSSL or STSOL", "Positive skills assessment", "IELTS 6+ or equivalent", "No health/character issues"],
    documents: ["Skills assessment", "Language test results", "Work experience proof", "Degree certificates", "Police clearance", "Medical exam", "Passport"],
    steps: ["Choose correct visa subclass (189/190/491)", "Get skills assessed", "Submit EOI in SkillSelect", "Receive invitation to apply", "Lodge visa application within 60 days", "Complete health checks", "Receive visa grant"],
    benefits: ["Permanent residency (189/190)", "Regional pathway (491 → 191 PR)", "Work anywhere in Australia", "Medicare access", "Children's free education"],
  },
  {
    title: "Australia Student Visa", country: "Australia", slug: "student-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "Australia is a top destination with 78.5% employment rate within 4–6 months of graduation. Students on Subclass 500 can work 48 hours per fortnight during studies.",
    processing: "4–6 weeks",
    fee: "AUD 710",
    eligibility: ["Confirmation of Enrolment (CoE) from CRICOS institution", "IELTS 5.5–6.5+ (varies by course)", "Genuine Temporary Entrant (GTE) statement", "Sufficient funds: AUD 21,041/year", "Overseas Student Health Cover (OSHC)", "Health & character requirements"],
    documents: ["CoE from institution", "Valid passport", "IELTS/PTE scores", "Financial evidence", "GTE statement", "OSHC insurance certificate", "Academic transcripts"],
    steps: ["Receive CoE from Australian institution", "Arrange OSHC health cover", "Submit online visa application", "Provide biometrics", "Complete health exam if required", "Receive student visa grant"],
    benefits: ["Work 48 hrs/fortnight during study", "Full-time work during holidays", "Post-Study Work visa (2–4 years after graduation)", "Pathway to PR via skilled migration", "World-class universities"],
  },
  {
    title: "Australia Work Visa", country: "Australia", slug: "work-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "Australia has 800,000+ job vacancies with an average salary of AUD 84,831. The TSS (482) and ENS (186) visas are the most popular employer-sponsored work pathways.",
    processing: "2–4 months",
    fee: "AUD 2,645–5,755",
    eligibility: ["Employer sponsorship required", "Occupation on relevant skilled list", "2+ years relevant work experience", "English proficiency", "Skills assessment (for some streams)", "Health & character clearances"],
    documents: ["Employer sponsorship documents", "Employment contract", "Work experience evidence", "IELTS/PTE scores", "Educational qualifications", "Passport", "Medical exam"],
    steps: ["Employer becomes approved sponsor", "Employer nominates position", "Submit work visa application", "Provide biometrics & health exam", "Receive work visa grant", "Travel to Australia & commence work"],
    benefits: ["Average salary AUD 84,831/year", "Bring spouse & dependents", "Pathway to PR (ENS/RSMS)", "Access to excellent healthcare", "72% skilled worker visa share"],
  },
  {
    title: "Australia Partner Visa", country: "Australia", slug: "partner-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "The Australia Partner Visa (Subclass 820/801 onshore or 309/100 offshore) allows spouses and de facto partners of Australian citizens or PR holders to live in Australia permanently.",
    processing: "12–24 months",
    fee: "AUD 8,850",
    eligibility: ["Genuine relationship with Australian citizen/PR", "Married or de facto (12+ months co-habitation)", "Meet health & character requirements", "Sponsor meets eligibility criteria"],
    documents: ["Relationship evidence (photos, joint financials)", "Marriage certificate / de facto evidence", "Sponsor's citizenship/PR proof", "Passport", "Medical exam", "Police clearance"],
    steps: ["Gather relationship evidence", "Lodge partner visa application", "Bridging visa issued (if onshore)", "Relationship assessed by Department of Home Affairs", "Receive temporary partner visa", "Assessed again after 2 years", "Permanent partner visa granted"],
    benefits: ["Live permanently in Australia", "Full work rights while application pending", "Medicare access", "Pathway to Australian citizenship", "Children can be included in application"],
  },
  {
    title: "Australia Business Visa", country: "Australia", slug: "business-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "Australia's Business Innovation and Investment Program (BIIP) includes streams for business owners, investors, and entrepreneurs seeking to establish or invest in an Australian business.",
    processing: "24–48 months",
    fee: "AUD 5,310+",
    eligibility: ["Proven business track record (minimum 2 years)", "Net assets meeting program threshold", "State/Territory nomination required", "Age under 55 (some streams)", "English proficiency"],
    documents: ["Business financial statements (4 years)", "Net assets evidence", "Comprehensive business plan", "State nomination documents", "Passport", "Police clearance", "Health exam"],
    steps: ["Choose appropriate business stream", "Submit EOI in SkillSelect", "Receive state/territory nomination", "Lodge visa application", "Provide health & character documents", "Receive provisional visa", "Establish business & meet performance criteria", "Apply for permanent residence"],
    benefits: ["PR for you & entire family", "Operate your own business in Australia", "Access the Australian market", "Free education for children", "Pathway to Australian citizenship"],
  },
  {
    title: "Australia Visit Visa", country: "Australia", slug: "visit-visa", countrySlug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80&auto=format&fit=crop",
    accentColor: "yellow",
    overview: "The Australia Visitor Visa (Subclass 600) allows tourism, visiting family, or short business trips. It can be granted for 3, 6, or 12 months with single or multiple entry.",
    processing: "Up to 20 days",
    fee: "AUD 135",
    eligibility: ["Valid passport (6+ months)", "Sufficient funds for stay", "Genuine intention to visit temporarily", "Strong ties to India", "Health & character requirements"],
    documents: ["Valid passport", "Online application form", "Bank statements (6 months)", "Salary slips & ITR", "Flight & hotel bookings", "Travel insurance", "Employment letter"],
    steps: ["Gather all documents", "Submit online application via ImmiAccount", "Pay AUD 135 visa fee", "Provide biometrics if required", "Await decision (up to 20 days)", "Travel to Australia"],
    benefits: ["Stay 3, 6, or 12 months", "Multiple entry options available", "Tourism, family visits, business meetings", "Covers all Australian states & territories"],
  },

  // ─── UNITED KINGDOM ──────────────────────────────────────────────────────
  {
    title: "UK Skilled Worker Visa", country: "United Kingdom", slug: "skilled-worker-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Skilled Worker Visa allows you to work for an approved UK employer in an eligible role. Over 200,000 Indians received UK work visas in 2024, making it one of the most popular routes.",
    processing: "3 weeks (outside UK)",
    fee: "GBP 610–1,408 + Immigration Health Surcharge",
    eligibility: ["Job offer from UK licensed sponsor", "Job on eligible occupation list", "Minimum salary GBP 38,700 (or going rate)", "English language proficiency (B1 level)", "70 points total requirement met"],
    documents: ["Certificate of Sponsorship (CoS) from employer", "Valid passport", "Proof of English language (IELTS/equivalent)", "Bank statements (GBP 1,270 for 28 days)", "TB test results (from India)", "Passport photos"],
    steps: ["Secure job offer from UK licensed sponsor", "Receive Certificate of Sponsorship", "Check you meet 70-point requirement", "Apply online for Skilled Worker Visa", "Provide biometrics at VAC", "Receive visa decision (3 weeks)", "Travel to UK & start work"],
    benefits: ["Work in the UK for approved employer", "Bring spouse & children as dependents", "Settle permanently after 5 years (ILR)", "Pathway to British citizenship", "Access to NHS healthcare", "Average salary £682/week"],
  },
  {
    title: "UK Student Visa", country: "United Kingdom", slug: "student-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Student Visa allows study at a UK institution licensed by UKVI. The UK offers world-renowned universities and 1-year Master's programmes. After graduation, the Graduate Route allows 2 years of work.",
    processing: "3 weeks",
    fee: "GBP 490 + Immigration Health Surcharge",
    eligibility: ["Confirmation of Acceptance for Studies (CAS)", "IELTS 5.5–7.0 (varies by course)", "Sufficient funds: GBP 1,334/month (London) or GBP 1,023/month (outside London)", "No TB or character issues"],
    documents: ["CAS reference number from institution", "Valid passport", "IELTS/PTE scores", "Bank statements (28 days)", "ATAS certificate (if required)", "Passport photos", "TB test certificate"],
    steps: ["Get unconditional offer from UK university", "Receive CAS reference number", "Apply online for Student Visa", "Pay visa fee & Immigration Health Surcharge", "Book biometrics at VAC", "Receive visa decision", "Travel to UK for studies"],
    benefits: ["Study at top universities (Oxford, Cambridge, Imperial)", "Work 20 hrs/week during term", "Graduate Route: 2 years work after graduation", "Pathway to Skilled Worker Visa", "1-year Master's programmes available"],
  },
  {
    title: "UK Graduate Visa", country: "United Kingdom", slug: "graduate-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Graduate Route allows international students who have completed a UK degree to stay and work in the UK for up to 2 years (3 years for PhD graduates). No job offer required.",
    processing: "8 weeks",
    fee: "GBP 715",
    eligibility: ["Completed eligible UK degree at licensed institution", "Currently in UK on valid Student Visa", "Apply before Student Visa expires", "Meet character requirements"],
    documents: ["Valid passport", "Current Student Visa", "UK degree certificate or transcript", "Proof of course completion from university"],
    steps: ["Complete your UK degree", "Apply for Graduate Route before Student Visa expires", "Pay GBP 715 fee", "Await decision (up to 8 weeks)", "Receive Graduate Route Visa", "Work or look for work in the UK"],
    benefits: ["2 years work in UK (3 years for PhD graduates)", "Work for any employer in any role", "No job offer required", "Pathway to Skilled Worker Visa", "No restriction on salary level"],
  },
  {
    title: "UK Spouse Visa", country: "United Kingdom", slug: "spouse-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Spouse Visa allows you to join your spouse or partner who is a British citizen or settled person in the UK. It leads to Indefinite Leave to Remain (ILR) after 5 years.",
    processing: "12 weeks",
    fee: "GBP 1,846 + Immigration Health Surcharge",
    eligibility: ["Genuine relationship with UK citizen/settled person", "Sponsor earns minimum GBP 29,000/year", "Both parties are 18+", "Adequate accommodation available", "English language requirement (A1 level)"],
    documents: ["Marriage certificate / proof of relationship", "Sponsor's passport & visa/citizenship proof", "Proof of sponsor's income (payslips, P60)", "Accommodation proof", "English language certificate", "Passport photos"],
    steps: ["Gather relationship & financial evidence", "Apply online for Spouse Visa", "Pay fee & IHS", "Provide biometrics at VAC", "Await decision (up to 12 weeks)", "Travel to UK & join spouse"],
    benefits: ["Live with spouse/partner in UK", "Full work rights in UK", "ILR after 5 years", "British citizenship pathway", "Children can be included in application"],
  },
  {
    title: "UK Business Visa", country: "United Kingdom", slug: "business-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Business Visit Visa allows attendance at meetings, conferences, training, or trade negotiations in the UK. Does not permit employment or payment from a UK source.",
    processing: "3 weeks",
    fee: "GBP 115",
    eligibility: ["Genuine business purpose", "Sufficient funds for trip", "Strong ties to India", "Intention to leave UK after visit", "Clean immigration record"],
    documents: ["Valid passport", "Business invitation letter", "Company registration proof", "Bank statements", "Travel & accommodation bookings", "Employment letter"],
    steps: ["Gather business & financial documents", "Apply online for Standard Visitor Visa", "Pay GBP 115 fee", "Book biometrics at VAC", "Attend biometrics appointment", "Await decision", "Travel to UK"],
    benefits: ["Attend meetings, conferences & training", "Multiple entry (valid up to 10 years)", "Stay up to 6 months per visit", "Covers all business activities (no employment)"],
  },
  {
    title: "UK Innovator Visa", country: "United Kingdom", slug: "innovator-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Innovator Founder Visa is for experienced businesspeople seeking to establish an innovative, viable, and scalable business in the UK. Requires endorsement from an approved body.",
    processing: "3 weeks",
    fee: "GBP 1,486",
    eligibility: ["Innovative, viable and scalable business idea", "Endorsement from approved UK body", "At least GBP 50,000 investment funds", "English proficiency (B2 level)", "Meet maintenance requirement"],
    documents: ["Endorsement letter from approved body", "Comprehensive business plan", "Proof of investment funds", "English language certificate", "Valid passport", "Bank statements"],
    steps: ["Develop innovative business idea", "Apply to an approved endorsing body", "Receive endorsement letter", "Apply for Innovator Founder Visa", "Travel to UK", "Establish & grow your business", "Apply for ILR after 3 years"],
    benefits: ["Permanent settlement (ILR) after 3 years", "Bring family to UK", "Work on your own business", "Access to UK market & investors", "Pathway to British citizenship"],
  },
  {
    title: "UK Visit Visa", country: "United Kingdom", slug: "visit-visa", countrySlug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200&q=80&auto=format&fit=crop",
    accentColor: "blue",
    overview: "The UK Standard Visitor Visa allows Indian citizens to visit the UK for tourism, family visits, or short business trips for up to 6 months. Long-term visit visas are available for up to 10 years.",
    processing: "Within 3 weeks",
    fee: "GBP 89 (6 months) · GBP 432 (5 years) · GBP 963 (10 years)",
    eligibility: ["Valid passport (6+ months)", "Sufficient funds for stay", "Genuine tourist/visitor purpose", "Strong ties to India", "Clean immigration history"],
    documents: ["Valid passport", "Online application form", "Bank statements (6 months)", "Salary slips & ITR", "Flight & accommodation bookings", "Invitation letter (if visiting family)", "Employment letter"],
    steps: ["Apply online for UK Visitor Visa", "Pay fee based on visa duration required", "Book biometrics appointment at VAC", "Provide biometrics & documents", "Await decision (within 3 weeks)", "Travel to UK"],
    benefits: ["Stay up to 6 months per visit", "Long-term visa up to 10 years available", "Tourism, family visits & business meetings", "Multiple entry on long-term visas"],
  },

  // ─── UNITED STATES ───────────────────────────────────────────────────────
  {
    title: "USA H-1B Visa", country: "United States", slug: "h1b-visa", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The H-1B is a non-immigrant visa for specialty occupations requiring at least a bachelor's degree. It is the most popular US work visa for Indian professionals, with 5.4 million Indians residing in the US.",
    processing: "3–5 months",
    fee: "USD 460 + employer fees",
    eligibility: ["Bachelor's degree or equivalent in specialty field", "Job offer from US employer willing to sponsor", "Employer must file H-1B petition", "Annual lottery applies (85,000 cap per year)", "Specialty occupation requirement"],
    documents: ["I-129 petition from employer", "Educational degrees & transcripts", "Work experience letters", "Valid passport", "DS-160 form", "Visa fee receipt", "Appointment confirmation"],
    steps: ["Employer files LCA with Department of Labor", "Employer submits H-1B petition (I-129) to USCIS", "USCIS lottery selection (April registration)", "Receive approval notice (I-797)", "Apply for H-1B visa at US consulate", "Attend visa interview", "Travel to USA & begin work"],
    benefits: ["Average IT salary USD 130,040/year", "Bring spouse on H-4 visa", "H-4 EAD work authorization for spouse", "Pathway to Green Card (EB-1/EB-2/EB-3)", "6-year initial stay (3+3 years)"],
  },
  {
    title: "USA Green Card", country: "United States", slug: "green-card", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "A US Green Card grants permanent residency allowing you to live and work in the US indefinitely. Employment-based Green Cards (EB-1 to EB-5) are the main pathway for skilled Indian professionals.",
    processing: "1–10+ years (varies by category & priority date)",
    fee: "USD 1,440 (adjustment of status)",
    eligibility: ["Employment-based: Employer sponsorship + PERM labor certification", "EB-1: Extraordinary ability / multinational managers", "EB-2: Advanced degree or exceptional ability", "EB-3: Skilled workers & professionals", "EB-5: Investment USD 800,000+"],
    documents: ["I-140 immigrant petition", "Labor certification (PERM) if applicable", "I-485 adjustment of status or DS-260 (consular)", "Medical examination (I-693)", "Police clearances", "Valid passport", "Affidavit of support (I-864)"],
    steps: ["Employer files PERM labor certification", "Employer files I-140 immigrant petition", "Wait for priority date to become current", "File I-485 adjustment of status (if in US)", "Attend biometrics & medical exam", "Attend interview if required", "Receive Green Card"],
    benefits: ["Live & work in USA indefinitely", "Travel freely (re-entry permit for long absences)", "Sponsor spouse & minor children", "Eligible for US citizenship after 5 years", "Access to federal public benefits"],
  },
  {
    title: "USA Student Visa", country: "United States", slug: "student-visa", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The F-1 Student Visa is for academic studies at US universities. The USA has 337,630 Indian students studying at world-class institutions including MIT, Harvard, and Stanford.",
    processing: "3–5 weeks",
    fee: "USD 185 (MRV fee) + SEVIS fee USD 350",
    eligibility: ["Acceptance from SEVP-approved institution", "IELTS 6.5+ / TOEFL 80+ (varies by university)", "Financial proof: USD 30,000–50,000/year", "Strong home country ties", "English proficiency demonstrated"],
    documents: ["Form I-20 from institution", "Valid passport", "SEVIS fee payment receipt", "DS-160 application form", "IELTS/TOEFL/GRE/GMAT scores", "Bank statements", "Academic transcripts"],
    steps: ["Apply & get accepted to SEVP-approved school", "Pay SEVIS fee & receive I-20", "Complete DS-160 form online", "Pay MRV visa fee", "Schedule & attend visa interview at US consulate", "Provide biometrics", "Receive F-1 visa & travel to USA"],
    benefits: ["Study at world's top universities (MIT, Harvard, Stanford)", "Work 20 hrs/week on campus", "OPT: 12 months work after graduation (24-month STEM extension)", "Pathway to H-1B work visa", "Excellent post-study employment prospects"],
  },
  {
    title: "USA L-1 Visa", country: "United States", slug: "l1-visa", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The L-1 visa allows multinational companies to transfer employees from a foreign office to the US. L-1A is for managers/executives; L-1B is for employees with specialized knowledge.",
    processing: "2–4 months (regular) · 15 days (premium processing)",
    fee: "USD 460 + employer fees",
    eligibility: ["Employed by multinational company for 1+ year in last 3 years", "L-1A: Manager or executive role", "L-1B: Specialized knowledge of company products/processes", "US company must be affiliate, parent, or subsidiary of foreign company"],
    documents: ["Employer petition (I-129)", "Proof of qualifying relationship between companies", "Employment letters & org charts", "Job description for US role", "Valid passport", "DS-160 form"],
    steps: ["Employer files I-129 petition with USCIS", "Receive USCIS approval notice (I-797)", "Apply for L-1 visa at US consulate", "Attend visa interview", "Travel to USA for intracompany transfer"],
    benefits: ["No annual lottery (unlike H-1B)", "L-1A: Pathway to EB-1C Green Card", "Bring spouse (L-2) and children", "L-2 spouse can work in USA", "Initial 3-year stay (L-1A: 7 years total, L-1B: 5 years)"],
  },
  {
    title: "USA O-1 Visa", country: "United States", slug: "o1-visa", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The O-1 visa is for individuals with extraordinary ability in sciences, arts, education, business, or athletics. No annual cap applies, making it an excellent alternative to H-1B.",
    processing: "2–4 months",
    fee: "USD 460 + employer/agent fees",
    eligibility: ["Extraordinary ability: National or international acclaim", "O-1A: Sciences, education, business, or athletics", "O-1B: Arts, motion picture, or TV productions", "Evidence of awards, publications, high salary, or critical role"],
    documents: ["Employer/agent petition (I-129)", "Evidence of extraordinary ability (awards, publications, press)", "Expert opinion letters", "Employment contract", "Valid passport"],
    steps: ["Gather evidence of extraordinary ability", "Employer or agent files I-129 petition with USCIS", "Receive USCIS approval", "Apply for O-1 visa at US consulate", "Attend interview", "Travel to USA"],
    benefits: ["No annual cap unlike H-1B", "Renewable in 1-year increments", "Bring family on O-3 visa", "Pathway to EB-1A Green Card", "Work for multiple employers with agent petition"],
  },
  {
    title: "USA EB-5 Investor", country: "United States", slug: "eb5-investor", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The EB-5 Immigrant Investor Program grants a Green Card to foreign nationals who invest at least USD 800,000 in a US business that creates 10 full-time jobs for US workers.",
    processing: "2–5 years",
    fee: "USD 800,000 (TEA) or USD 1,050,000 (standard area) investment",
    eligibility: ["Minimum investment: USD 800,000 (Targeted Employment Area) or USD 1,050,000", "Create or preserve 10 full-time jobs for US workers", "Lawful source of investment funds", "No criminal history"],
    documents: ["Evidence of investment & source of funds", "Comprehensive business plan", "I-526 immigrant petition", "Bank records & tax returns", "Valid passport", "Medical exam"],
    steps: ["Choose direct investment or Regional Center investment", "Transfer investment funds", "File I-526 petition with USCIS", "Apply for immigrant visa or adjustment of status", "Receive conditional Green Card (2 years)", "File I-829 to remove conditions", "Receive permanent Green Card"],
    benefits: ["Permanent residency for investor & entire family", "No employment or language requirements", "Spouse & children under 21 included", "Children can attend US schools", "Pathway to US citizenship after 5 years"],
  },
  {
    title: "USA B-1/B-2 Visit Visa", country: "United States", slug: "b1b2-visit", countrySlug: "united-states",
    image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1200&q=80&auto=format&fit=crop",
    accentColor: "indigo",
    overview: "The US B-1/B-2 visa covers business visits (B-1) and tourism/family visits (B-2). Can be issued for up to 10 years with multiple entries, allowing stays of up to 6 months per visit.",
    processing: "3–5 weeks + 2 days delivery",
    fee: "USD 160",
    eligibility: ["Valid passport", "Strong ties to India (job, family, property)", "Sufficient funds for trip", "Genuine purpose of visit", "Intention to return to India after visit"],
    documents: ["DS-160 form (online)", "Valid passport", "Bank statements", "Income proof (salary slips, ITR)", "US itinerary & hotel bookings", "Invitation letter (if visiting family/business)", "Employment letter"],
    steps: ["Complete DS-160 online form", "Pay USD 160 visa fee", "Schedule visa interview at US consulate", "Attend in-person interview with documents", "Provide biometrics", "Receive visa (7–10 days after interview)", "Travel to USA"],
    benefits: ["Valid up to 10 years, multiple entry", "Stay up to 6 months per visit", "Tourism, family visits & business meetings", "Covers both B-1 (business) and B-2 (tourist) activities"],
  },

  // ─── GERMANY ─────────────────────────────────────────────────────────────
  {
    title: "Germany Job Seeker Visa", country: "Germany", slug: "job-seeker-visa", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "Germany's Job Seeker Visa allows qualified professionals to travel to Germany for 6 months to find a job. Once a job offer is secured, it can be converted to a work visa or EU Blue Card.",
    processing: "4–8 weeks",
    fee: "EUR 75",
    eligibility: ["Recognised university degree (German or equivalent)", "Minimum 5 years professional experience", "Basic German language skills preferred", "Proof of sufficient funds: EUR 5,000+ for stay", "Health insurance coverage for duration of stay"],
    documents: ["Valid passport", "University degree (with certified German translation)", "Professional CV / Resume", "Proof of funds (bank statements)", "Health insurance proof", "Accommodation proof in Germany", "Cover letter"],
    steps: ["Gather documents & get degree recognised", "Apply at German consulate in India", "Attend visa interview", "Receive 6-month Job Seeker Visa", "Travel to Germany & search for job", "Secure job offer from German employer", "Convert to work visa / EU Blue Card"],
    benefits: ["6 months to find a job in Germany", "Germany has 880,000+ job vacancies", "Average salary EUR 51,000/year", "Pathway to EU Blue Card or work permit", "Gateway to all 27 EU countries"],
  },
  {
    title: "Germany Work Visa", country: "Germany", slug: "work-visa", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "Germany actively recruits skilled workers globally with 880,000+ vacancies. The German Work Visa is for professionals with a job offer from a German employer in a skilled occupation.",
    processing: "1–3 months",
    fee: "EUR 75–100",
    eligibility: ["Recognised qualification (university degree or vocational training)", "Binding job offer from German employer", "German or CEFR B1+ language skills (for some roles)", "Positive decision from Federal Employment Agency"],
    documents: ["Valid passport", "Job offer / employment contract", "Educational qualifications (with official recognition)", "CV in German format (Lebenslauf)", "Language proficiency certificate", "Passport photos"],
    steps: ["Get job offer from German employer", "Have qualifications recognised (anabin database)", "Apply at German consulate in India", "Federal Employment Agency approves the position", "Receive work visa", "Travel to Germany & register at local residents' office"],
    benefits: ["Average salary EUR 51,000/year", "Strong social security & healthcare system", "Family reunification possible", "Pathway to EU Blue Card", "Permanent settlement after 4 years", "Gateway to all 27 EU countries"],
  },
  {
    title: "Germany EU Blue Card", country: "Germany", slug: "eu-blue-card", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "The EU Blue Card is Germany's premium work permit for highly qualified professionals. It offers faster permanent residence (21 months with German B1) and is one of the easiest ways for skilled Indians to settle in Germany.",
    processing: "1–3 months",
    fee: "EUR 100",
    eligibility: ["University degree recognised in Germany", "Job offer with minimum salary EUR 45,300/year (shortage occupations: EUR 35,100)", "Degree relevant to job position", "No criminal record"],
    documents: ["Valid passport", "University degree + official recognition letter", "Employment contract (with salary stated)", "Proof of health insurance", "Biometric passport photos", "CV (Lebenslauf)"],
    steps: ["Get university degree recognised in Germany", "Secure job offer meeting the salary threshold", "Apply at German consulate in India", "Receive EU Blue Card", "Register at local residents' office (Einwohnermeldeamt)", "After 21–33 months: apply for permanent settlement permit"],
    benefits: ["Permanent residence after just 21 months (with B1 German)", "Bring family immediately upon arrival", "Family members can work without restrictions", "Valid across EU countries", "Pathway to German citizenship after 6–8 years"],
  },
  {
    title: "Germany Student Visa", country: "Germany", slug: "student-visa", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "Germany offers tuition-free education at public universities (only EUR 300–400/semester admin fees). One of the best destinations for Indian students seeking world-class education at minimal cost.",
    processing: "6–12 weeks",
    fee: "EUR 75",
    eligibility: ["Admission to recognised German university", "German B2/C1 or English proficiency (for English-taught programmes)", "Proof of funds: EUR 11,208/year via blocked account (Sperrkonto)", "Health insurance", "No criminal record"],
    documents: ["University admission letter", "Valid passport", "German/English language certificate", "Proof of blocked account (EUR 11,208)", "Academic transcripts", "Health insurance proof", "Motivation letter"],
    steps: ["Apply to German university (summer/winter intake)", "Open blocked account (Sperrkonto) with EUR 11,208", "Apply for Student Visa at German consulate", "Attend visa interview", "Receive visa & travel to Germany", "Register at university & complete enrolment"],
    benefits: ["Free tuition at public universities (only EUR 300–400 admin fees)", "Work 20 hrs/week during studies", "18-month job search visa after graduation", "Pathway to EU Blue Card / Work Visa", "Low cost of living vs UK/USA/Canada"],
  },
  {
    title: "Germany Business Visa", country: "Germany", slug: "business-visa", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "The Germany Business Visa allows professionals to attend business meetings, conferences, trade fairs, or negotiate contracts in Germany and other Schengen countries for up to 90 days.",
    processing: "2–4 weeks",
    fee: "EUR 80 (Schengen visa)",
    eligibility: ["Valid passport", "Business invitation from German company", "Sufficient funds for trip", "Return flight ticket", "Health insurance (EUR 30,000 minimum coverage)", "Ties to home country"],
    documents: ["Valid passport", "Business invitation letter from German company", "Company registration / employment proof", "Bank statements (3–6 months)", "Travel & accommodation bookings", "Travel insurance", "Passport photos"],
    steps: ["Gather business & financial documents", "Apply at German consulate in India", "Pay EUR 80 fee", "Attend visa interview if required", "Receive Schengen visa", "Travel to Germany & other Schengen countries"],
    benefits: ["Valid for all 26 Schengen countries", "Attend trade fairs (e.g. Hannover Messe, Frankfurt Motor Show)", "Stay up to 90 days in any 180-day period", "Multiple entry option available"],
  },
  {
    title: "Germany Family Reunion", country: "Germany", slug: "family-reunion", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "The Germany Family Reunification Visa allows spouses, children, and in some cases parents of German residents or citizens to join their family member in Germany.",
    processing: "3–6 months",
    fee: "EUR 75",
    eligibility: ["Sponsor must be German citizen or legal resident with valid permit", "Genuine family relationship", "Basic German language (A1) for spouses joining non-EU citizens", "Adequate accommodation & sufficient income in Germany"],
    documents: ["Marriage certificate / birth certificate", "Sponsor's passport & German residence permit", "Proof of accommodation in Germany", "Proof of sponsor's income", "Basic German language certificate (A1)", "Valid passport of applicant"],
    steps: ["Sponsor confirms eligibility & gathers documents", "Applicant applies at German consulate in India", "Attend consulate interview", "Await decision (3–6 months)", "Travel to Germany on approval", "Register at local authority (Einwohnermeldeamt)", "Apply for residence permit in Germany"],
    benefits: ["Reunite with family in Germany", "Spouse can work in Germany", "Children get free education", "Pathway to permanent residence", "Access to German healthcare & social benefits"],
  },
  {
    title: "Germany Visit Visa", country: "Germany", slug: "visit-visa", countrySlug: "germany",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80&auto=format&fit=crop",
    accentColor: "slate",
    overview: "The Germany Schengen Visa allows travel to Germany and all 26 Schengen countries for tourism, family visits, or cultural events for up to 90 days in any 180-day period.",
    processing: "15 working days",
    fee: "EUR 80",
    eligibility: ["Valid passport (3 months beyond travel dates)", "Travel insurance EUR 30,000+ coverage", "Proof of accommodation & return ticket", "Sufficient funds (EUR 45/day recommended)", "No previous Schengen visa violation"],
    documents: ["Valid passport", "Schengen visa application form", "Travel insurance certificate", "Flight & hotel bookings", "Bank statements (3 months)", "Salary slips & employment letter", "Invitation letter (if applicable)", "Passport photos"],
    steps: ["Apply at German consulate (if Germany is main destination or first entry)", "Submit complete documents", "Pay EUR 80 fee", "Attend interview if required", "Await decision (15 working days)", "Travel to Germany & 25 other Schengen countries"],
    benefits: ["Access to all 26 Schengen countries with one visa", "Stay up to 90 days in any 180-day period", "Tourism, family visits & cultural events", "Multiple entry option available"],
  },

  // ─── UAE ─────────────────────────────────────────────────────────────────
  {
    title: "UAE Work Visa", country: "UAE", slug: "work-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Employment Visa allows skilled workers to live and work in the UAE. With zero income tax, 418,500+ job vacancies annually, and an average salary of AED 191,807/year, the UAE is one of the best destinations for Indian professionals.",
    processing: "~15 working days",
    fee: "AED 300–600",
    eligibility: ["Valid job offer from UAE employer", "Educational qualifications relevant to role", "Valid passport (6+ months)", "Medical fitness test", "Emirates ID registration"],
    documents: ["Valid passport", "Signed employment contract", "Educational certificates (attested)", "Passport photos", "Medical test results", "Emirates ID application form"],
    steps: ["Receive job offer from UAE employer", "Employer initiates visa process with MOL", "Entry permit issued", "Travel to UAE", "Complete medical fitness test", "Apply for Emirates ID", "Receive residency visa stamped in passport"],
    benefits: ["Zero income tax", "Average salary AED 191,807/year", "418,500+ job vacancies annually", "77.43% employment rate", "Dynamic multicultural expat environment", "Bring family as dependents"],
  },
  {
    title: "UAE Golden Visa", country: "UAE", slug: "golden-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Golden Visa is a long-term residency visa (5 or 10 years) for investors, entrepreneurs, exceptional talents, scientists, and outstanding students. It provides long-term stability to live, work, and study in the UAE.",
    processing: "30 days",
    fee: "AED 2,800–4,000",
    eligibility: ["Investors: AED 2 million+ in UAE property or business", "Entrepreneurs: Approved UAE project or startup", "Exceptional talents: Doctors, scientists, artists, athletes", "Outstanding students: GPA 3.75+ from top universities", "Specialised talents: Coders, senior executives, doctors"],
    documents: ["Valid passport", "UAE residence visa (if applicable)", "Proof of investment / achievement", "Educational certificates (for student category)", "Business plan (for entrepreneurs)", "Passport photos"],
    steps: ["Determine your Golden Visa eligibility category", "Gather relevant supporting documents", "Apply through UAE General Directorate of Residency (GDRFA)", "Receive entry permit", "Complete medical exam & Emirates ID", "Receive Golden Visa (5 or 10 years)"],
    benefits: ["Long-term residency (5 or 10 years) — renewable", "Live without an employer sponsor", "Sponsor family members", "100% business ownership allowed", "No restrictions on career changes", "Prestige & long-term stability in UAE"],
  },
  {
    title: "UAE Business Visa", country: "UAE", slug: "business-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Business Visa allows professionals to visit the UAE for meetings, conferences, trade shows, or to explore business opportunities. Dubai is a global business hub hosting thousands of international events annually.",
    processing: "3–5 working days",
    fee: "AED 350–500",
    eligibility: ["Valid passport (6+ months)", "Business invitation from UAE company", "Proof of sufficient funds", "Return flight ticket", "Health insurance"],
    documents: ["Valid passport", "Business invitation letter from UAE company", "Company registration documents", "Bank statements", "Return flight booking", "Hotel accommodation confirmation"],
    steps: ["Obtain invitation letter from UAE company", "Apply for business visit visa online or through agent", "Submit all required documents", "Receive visa approval (3–5 days)", "Travel to UAE for business activities"],
    benefits: ["Access to Dubai, Abu Dhabi, Sharjah business events", "Multiple entry option available", "Stay up to 30 or 90 days", "Zero income tax business environment", "World-class infrastructure & connectivity"],
  },
  {
    title: "UAE Student Visa", country: "UAE", slug: "student-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Student Visa allows international students to study at UAE universities and colleges. The UAE is home to international branches of top global universities including NYU Abu Dhabi and University of Birmingham Dubai.",
    processing: "2–4 weeks",
    fee: "AED 500–1,000",
    eligibility: ["Acceptance letter from UAE institution", "Valid passport", "Medical fitness test", "No criminal record", "Financial ability to support studies & living costs"],
    documents: ["Acceptance letter from UAE university", "Valid passport", "Passport photos", "Medical test results", "Financial proof", "Academic transcripts"],
    steps: ["Receive acceptance from UAE university", "University applies for student entry permit", "Travel to UAE on entry permit", "Complete medical fitness test", "Apply for student residence visa", "Register with university & begin studies"],
    benefits: ["World-class international university branches in UAE", "Safe, modern living environment", "Part-time work (with university approval)", "Dubai / Abu Dhabi metropolitan experience", "Multicultural campus environment"],
  },
  {
    title: "UAE Freelance Permit", country: "UAE", slug: "freelance-permit", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Freelance Permit allows professionals to work independently in the UAE without being tied to a single employer. Available in free zones like TECOM, Fujairah Creative City, and Ras Al Khaimah.",
    processing: "1–2 weeks",
    fee: "AED 7,500–15,000/year (free zone dependent)",
    eligibility: ["Relevant professional qualifications or strong portfolio", "Valid passport", "Proof of professional experience", "No UAE criminal record"],
    documents: ["Valid passport", "Professional portfolio or qualification certificates", "Passport photos", "Bank statements", "NOC letter (if currently employed in UAE)"],
    steps: ["Choose relevant UAE free zone for your profession", "Submit application with all documents", "Pay annual license fee", "Receive freelance permit", "Apply for residence visa through free zone", "Open UAE bank account & start working"],
    benefits: ["Work independently without employer sponsorship", "100% business ownership", "Work with multiple clients & on multiple projects", "Renewable annually", "Pathway to long-term UAE residency"],
  },
  {
    title: "UAE Spouse Visa", country: "UAE", slug: "spouse-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "UAE residents earning AED 4,000+ per month (or AED 3,000 + accommodation) can sponsor their spouse and children on a UAE dependent/family residency visa.",
    processing: "1–2 weeks",
    fee: "AED 2,000–3,500",
    eligibility: ["Sponsor must be UAE resident with valid residency visa", "Minimum salary AED 4,000/month (or AED 3,000 + accommodation)", "Valid rental agreement for adequate accommodation", "Attested marriage certificate"],
    documents: ["Sponsor's Emirates ID & passport", "Attested marriage certificate", "Valid rental agreement", "Salary certificate from employer", "Spouse's valid passport", "Passport photos", "Medical test results"],
    steps: ["Gather all attested documents", "Apply for entry permit for spouse", "Spouse travels to UAE on entry permit", "Complete medical test & Emirates ID application", "Receive dependent residency visa", "Renew along with sponsor's visa"],
    benefits: ["Family together in the UAE", "Spouse can apply for own UAE work permit", "Children can attend UAE schools", "Access to UAE healthcare", "Safe, family-friendly environment"],
  },
  {
    title: "UAE Visit Visa", country: "UAE", slug: "visit-visa", countrySlug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
    accentColor: "emerald",
    overview: "The UAE Visit Visa allows Indian citizens to visit Dubai and the UAE for tourism or family visits. Available as a 30-day or 90-day visa, single or multiple entry.",
    processing: "3–5 working days",
    fee: "AED 250–500",
    eligibility: ["Valid Indian passport (6+ months validity)", "Sufficient funds for stay", "Return flight ticket", "Hotel or host accommodation proof", "Clean immigration record"],
    documents: ["Valid passport", "Passport photos", "Return flight ticket", "Hotel booking confirmation", "Bank statement (3 months)", "Salary slip or employment letter"],
    steps: ["Apply online through UAE airline / travel agent / GDRFA", "Submit all required documents", "Receive visa approval (3–5 days)", "Travel to UAE", "Enjoy 30 or 90 days across Dubai, Abu Dhabi & beyond"],
    benefits: ["Fast processing in 3–5 working days", "30 or 90 days stay options", "Multiple entry option available", "Tax-free world-class shopping", "World-renowned tourism (Burj Khalifa, Desert Safari, Abu Dhabi)"],
  },
];

export function getVisa(countrySlug: string, visaSlug: string): VisaDetail | undefined {
  return visaData.find(v => v.countrySlug === countrySlug && v.slug === visaSlug);
}

export const accentClasses: Record<string, { bg: string; text: string; light: string; border: string; badge: string }> = {
  red: { bg: "bg-red-600", text: "text-red-600", light: "bg-red-50", border: "border-red-100", badge: "bg-red-50 text-red-700" },
  yellow: { bg: "bg-yellow-500", text: "text-yellow-600", light: "bg-yellow-50", border: "border-yellow-100", badge: "bg-yellow-50 text-yellow-700" },
  blue: { bg: "bg-blue-600", text: "text-blue-600", light: "bg-blue-50", border: "border-blue-100", badge: "bg-blue-50 text-blue-700" },
  indigo: { bg: "bg-indigo-600", text: "text-indigo-600", light: "bg-indigo-50", border: "border-indigo-100", badge: "bg-indigo-50 text-indigo-700" },
  slate: { bg: "bg-slate-700", text: "text-slate-700", light: "bg-slate-50", border: "border-slate-200", badge: "bg-slate-100 text-slate-700" },
  emerald: { bg: "bg-emerald-600", text: "text-emerald-600", light: "bg-emerald-50", border: "border-emerald-100", badge: "bg-emerald-50 text-emerald-700" },
};
